channels:
  - conda-forge
  - defaults

dependencies:
  - cmake
  - cmake-build-extension
  - make
  - matplotlib
  - ninja
  - numpy
  - pandas
  - pkg-config
  - pyYAML
  - pyparsing
  - pytest
  - pyzmq
  - scipy
  - sphinx_rtd_theme
  - treon
  - wisdem >=3.16
  - zeromq
  - openfast=4.1
  - openfast-io=4.1
  - pip:
    - control
